"""Run context tests. The env scrub is the part that matters most.

If a variable leaks in from the parent process, it becomes a channel between the
two runs that the probe was never asked about.
"""

import json
import shutil
import subprocess
import sys

import pytest

from runwarden.run_context import (
    ALLOWED_ENV_KEYS,
    RunContext,
    RunExecError,
    make_context,
    make_pair,
)

CANARY_NAME = "RUNWARDEN_TEST_CANARY"


def test_pair_has_different_run_ids(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    assert run_a.run_id != run_b.run_id
    assert len(run_a.run_id) == 12
    assert len(run_b.run_id) == 12


def test_pair_labels_are_a_and_b(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    assert run_a.label == "A"
    assert run_b.label == "B"


def test_pair_workdirs_are_disjoint(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    assert run_a.workdir != run_b.workdir
    assert not run_a.workdir.is_relative_to(run_b.workdir)
    assert not run_b.workdir.is_relative_to(run_a.workdir)


def test_pair_tmpdirs_are_disjoint(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    assert run_a.tmpdir != run_b.tmpdir
    assert not run_a.tmpdir.is_relative_to(run_b.tmpdir)
    assert not run_b.tmpdir.is_relative_to(run_a.tmpdir)


def test_pair_directories_exist(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    for run in (run_a, run_b):
        assert run.workdir.is_dir()
        assert run.tmpdir.is_dir()


def test_env_contains_exactly_the_four_allowed_keys(tmp_path, monkeypatch):
    monkeypatch.setenv(CANARY_NAME, "leaked")
    run_a, run_b = make_pair(tmp_path)
    for run in (run_a, run_b):
        assert set(run.env) == set(ALLOWED_ENV_KEYS)
        assert len(run.env) == 4


def test_canary_from_parent_env_is_absent(tmp_path, monkeypatch):
    monkeypatch.setenv(CANARY_NAME, "leaked")
    run_a, run_b = make_pair(tmp_path)
    for run in (run_a, run_b):
        assert CANARY_NAME not in run.env
        assert "leaked" not in run.env.values()


def test_env_home_and_tmpdir_point_at_the_run_directories(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    for run in (run_a, run_b):
        assert run.env["HOME"] == str(run.workdir)
        assert run.env["TMPDIR"] == str(run.tmpdir)
        assert run.env["RUNWARDEN_RUN_ID"] == run.run_id


def test_run_ids_in_env_are_not_shared(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    assert run_a.env["RUNWARDEN_RUN_ID"] != run_b.env["RUNWARDEN_RUN_ID"]


def test_label_must_be_a_or_b(tmp_path):
    with pytest.raises(ValueError, match="label"):
        RunContext(
            run_id="0123456789ab",
            label="C",
            workdir=tmp_path,
            tmpdir=tmp_path,
            env={},
        )


def test_run_id_length_is_enforced(tmp_path):
    with pytest.raises(ValueError, match="run_id"):
        RunContext(run_id="abc", label="A", workdir=tmp_path, tmpdir=tmp_path, env={})


def test_make_context_accepts_an_explicit_run_id(tmp_path):
    run = make_context(tmp_path, "A", run_id="0123456789ab")
    assert run.run_id == "0123456789ab"
    assert run.env["RUNWARDEN_RUN_ID"] == "0123456789ab"


def test_exec_runs_in_the_run_workdir(tmp_path):
    run_a, _ = make_pair(tmp_path)
    result = run_a.exec([sys.executable, "-c", "import os; print(os.getcwd())"])
    assert result.stdout.decode().strip() == str(run_a.workdir)


def test_exec_captures_stdout_and_stderr_as_bytes(tmp_path):
    run_a, _ = make_pair(tmp_path)
    code = "import sys; sys.stdout.write('out'); sys.stderr.write('err')"
    result = run_a.exec([sys.executable, "-c", code])
    assert result.stdout == b"out"
    assert result.stderr == b"err"


def test_exec_passes_exactly_the_four_keys_to_the_child(tmp_path, monkeypatch):
    """The whole isolation claim rests on this. A leaked variable is a channel.

    Checked through /usr/bin/env rather than through Python, because the Python
    interpreter adds LC_CTYPE to its own environment on startup (PEP 538 locale
    coercion) and that generated variable would obscure what was actually
    handed to the child.
    """
    env_binary = shutil.which("env")
    if env_binary is None:
        pytest.skip("env not on PATH")
    monkeypatch.setenv(CANARY_NAME, "leaked")
    run_a, _ = make_pair(tmp_path)
    lines = run_a.exec([env_binary]).stdout.decode().splitlines()
    keys = sorted(line.split("=", 1)[0] for line in lines if "=" in line)
    assert keys == sorted(ALLOWED_ENV_KEYS)


def test_exec_child_python_sees_no_parent_variable(tmp_path, monkeypatch):
    """Any key beyond the four is generated by the interpreter, not inherited."""
    monkeypatch.setenv(CANARY_NAME, "leaked")
    run_a, _ = make_pair(tmp_path)
    code = "import json, os; print(json.dumps(dict(os.environ)))"
    child_env = json.loads(run_a.exec([sys.executable, "-c", code]).stdout)
    assert CANARY_NAME not in child_env
    assert "leaked" not in child_env.values()
    extra = set(child_env) - set(ALLOWED_ENV_KEYS)
    assert extra <= {"LC_CTYPE"}


def test_exec_child_env_run_id_matches_the_context(tmp_path):
    run_a, run_b = make_pair(tmp_path)
    for run in (run_a, run_b):
        code = "import os; print(os.environ['RUNWARDEN_RUN_ID'])"
        assert run.exec([sys.executable, "-c", code]).stdout.decode().strip() == run.run_id


def test_exec_raises_on_non_zero_exit_and_carries_the_details(tmp_path):
    run_a, _ = make_pair(tmp_path)
    code = "import sys; sys.stderr.write('boom'); sys.exit(3)"
    with pytest.raises(RunExecError) as exc:
        run_a.exec([sys.executable, "-c", code])
    assert exc.value.returncode == 3
    assert exc.value.stderr == b"boom"
    assert exc.value.argv[0] == sys.executable
    assert "boom" in str(exc.value)


def test_exec_with_check_false_returns_the_failed_result(tmp_path):
    run_a, _ = make_pair(tmp_path)
    result = run_a.exec([sys.executable, "-c", "raise SystemExit(4)"], check=False)
    assert result.returncode == 4


def test_exec_does_not_use_a_shell(tmp_path):
    """An argument full of shell metacharacters must arrive literally."""
    run_a, _ = make_pair(tmp_path)
    hostile = "; touch pwned > /dev/null | $(echo no) `echo no`"
    code = "import sys; sys.stdout.write(sys.argv[1])"
    result = run_a.exec([sys.executable, "-c", code, hostile])
    assert result.stdout.decode() == hostile
    assert not (run_a.workdir / "pwned").exists()


def test_exec_passes_input_on_stdin(tmp_path):
    run_a, _ = make_pair(tmp_path)
    code = "import sys; sys.stdout.write(sys.stdin.read().upper())"
    assert run_a.exec([sys.executable, "-c", code], input=b"hello").stdout == b"HELLO"


def test_exec_without_input_closes_stdin(tmp_path):
    """A command that decides to prompt must fail, not block the probe forever."""
    run_a, _ = make_pair(tmp_path)
    code = "import sys; sys.stdout.write(repr(sys.stdin.read()))"
    assert run_a.exec([sys.executable, "-c", code]).stdout == b"''"


def test_exec_times_out(tmp_path):
    run_a, _ = make_pair(tmp_path)
    with pytest.raises(subprocess.TimeoutExpired):
        run_a.exec([sys.executable, "-c", "import time; time.sleep(5)"], timeout=0.5)


def test_python_runs_code_in_the_run_context(tmp_path):
    run_a, _ = make_pair(tmp_path)
    code = "import os; print(os.getcwd()); print(os.environ['RUNWARDEN_RUN_ID'])"
    lines = run_a.python(code).stdout.decode().splitlines()
    assert lines == [str(run_a.workdir), run_a.run_id]


def test_python_raises_on_failure(tmp_path):
    run_a, _ = make_pair(tmp_path)
    with pytest.raises(RunExecError):
        run_a.python("raise ValueError('nope')")


def test_python_with_check_false_reports_the_traceback(tmp_path):
    run_a, _ = make_pair(tmp_path)
    result = run_a.python("raise ValueError('nope')", check=False)
    assert result.returncode != 0
    assert b"nope" in result.stderr
